# Platform services configuration

postgres:
  image: postgres:14-alpine
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
  persistence:
    enabled: true
    size: 10Gi
  externalIP: ""  # Will be set at deployment time

minio:
  image: minio/minio:RELEASE.2023-06-19T19-52-50Z
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"
  persistence:
    enabled: true
    size: 20Gi
  externalIP: ""  # Will be set at deployment time

mlflow:
  image: ghcr.io/mlflow/mlflow:v2.20.2
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
    requests:
      cpu: "250m"
      memory: "512Mi"
  externalIP: ""  # Will be set at deployment time

githubWebhook:
  image: project32/github-webhook:latest
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  externalIP: ""  # Will be set at deployment time