apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-webhook
  namespace: project32-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-webhook
  template:
    metadata:
      labels:
        app: github-webhook
    spec:
      containers:
        - name: github-webhook
          image: {{ .Values.githubWebhook.image }}
          ports:
            - containerPort: 8080
          env:
            - name: GITHUB_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: github-credentials
                  key: webhook_secret
            - name: REVIEWER_BOT_STAGING_SERVICE
              value: http://reviewer-bot.project32-staging.svc.cluster.local:8080
            - name: REVIEWER_BOT_CANARY_SERVICE
              value: http://reviewer-bot.project32-canary.svc.cluster.local:8080
            - name: REVIEWER_BOT_PRODUCTION_SERVICE
              value: http://reviewer-bot.project32-production.svc.cluster.local:8080
          resources:
            {{- toYaml .Values.githubWebhook.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: github-webhook
  namespace: project32-platform
spec:
  selector:
    app: github-webhook
  ports:
    - port: 80
      targetPort: 8080
  externalIPs:
    - {{ .Values.githubWebhook.externalIP }}