apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-container-image
spec:
  entrypoint: kaniko-build-flow
  arguments:
    parameters:
    - name: model-version

  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi

  templates:
  - name: kaniko-build-flow
    steps:
      - - name: clone-repo
          template: git-clone
      - - name: fetch-model
          template: download-model
          arguments:
            parameters:
            - name: model-version
              value: "{{workflow.parameters.model-version}}"
      - - name: kaniko-build
          template: kaniko
          arguments:
            parameters:
            - name: model-version
              value: "{{workflow.parameters.model-version}}"
      - - name: tag-model-staging
          template: set-mlflow-alias
          arguments:
            parameters:
            - name: model-version
              value: "{{workflow.parameters.model-version}}"
      - - name: deploy-to-staging
          template: trigger-deploy
          arguments:
            parameters:
            - name: model-version
              value: "{{workflow.parameters.model-version}}"
            - name: environment
              value: "staging"

  - name: git-clone
    container:
      image: alpine/git
      command: [sh, -c]
      args:
        - |
          git clone --branch main https://github.com/BugBeak/MLOps.githttps://github.com/BugBeak/MLOps.git /mnt/workspace
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: download-model
    inputs:
      parameters:
      - name: model-version
    container:
      image: python:3.11-slim
      command: [sh, -c]
      args:
        - |
          pip install mlflow-skinny
          export MLFLOW_TRACKING_URI=http://mlflow.project32-platform.svc.cluster.local:8000
          mkdir -p /tmp/mlflow_model

          echo "Downloading MLflow model artifacts..."
          mlflow artifacts download \
            --artifact-uri models:/CodeReviewerModel/{{inputs.parameters.model-version}} \
            -d /tmp/mlflow_model || { echo "MLflow download failed"; exit 1; }

          echo "Copying model artifacts to workspace..."
          cp -r /tmp/mlflow_model/* /mnt/workspace/model/
          echo "1.0.{{inputs.parameters.model-version}}" > /mnt/workspace/versions.txt
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: kaniko
    inputs:
      parameters:
      - name: model-version
    container:
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=/mnt/workspace/Dockerfile
        - --context=/mnt/workspace
        - --destination=registry.kube-system.svc.cluster.local:5000/reviewer-bot:staging-1.0.{{inputs.parameters.model-version}}
        - --insecure
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: set-mlflow-alias
    inputs:
      parameters:
      - name: model-version
    script:
      image: python:3.11-slim
      command: [sh, -c]
      source: |
        pip install mlflow-skinny > /dev/null
        export MLFLOW_TRACKING_URI=http://mlflow.project32-platform.svc.cluster.local:8000
        python -c "import mlflow; client = mlflow.tracking.MlflowClient(); client.set_registered_model_alias(name='CodeReviewerModel', alias='staging', version='{{inputs.parameters.model-version}}')"
  
  - name: trigger-deploy
    inputs:
      parameters:
      - name: model-version
      - name: environment
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          generateName: deploy-container-image-
        spec:
          workflowTemplateRef:
            name: deploy-container-image
          arguments:
            parameters:
            - name: environment
              value: "{{inputs.parameters.environment}}"
            - name: model-version
              value: "{{inputs.parameters.model-version}}"