# build-container-image.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: build-container-image
spec:
  entrypoint: kaniko-build-flow

  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi

  templates:
  - name: kaniko-build-flow
    steps:
      - - name: clone-repo
          template: git-clone
      - - name: kaniko-build
          template: kaniko

  - name: git-clone
    container:
      image: alpine/git
      command: [sh, -c]
      args:
        - |
          MAX_RETRIES=5
          i=1
          while [ $i -le $MAX_RETRIES ]; do
            git clone --branch main https://github.com/BugBeak/MLOps.git /mnt/workspace && break
            i=$((i + 1))
            sleep 5
          done
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace

  - name: kaniko
    container:
      image: gcr.io/kaniko-project/executor:latest
      args:
        - --dockerfile=/mnt/workspace/Dockerfile
        - --context=/mnt/workspace
        - --destination=registry.kube-system.svc.cluster.local:5000/code-reviewer-app:latest
        - --insecure
      volumeMounts:
      - name: workdir
        mountPath: /mnt/workspace