# deploy-container-image.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: deploy-container-image
spec:
  entrypoint: deploy

  templates:
  - name: deploy
    inputs:
      parameters:
      - name: environment
    container:
      image: argoproj/argocd:latest
      command: [sh, -c]
      args:
        - |
          echo "Deploying latest build to {{inputs.parameters.environment}}..."
          app_name="code-reviewer-{{inputs.parameters.environment}}"
          argocd login argocd-server.argocd.svc.cluster.local \
            --username admin --password "$ARGOCD_PASSWORD" --insecure
          argocd app set "$app_name" --helm-set-string image.tag=latest
          argocd app sync "$app_name"
      env:
        - name: ARGOCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: argocd-initial-admin-secret
              key: password
