apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: promote-model
spec:
  entrypoint: promote-flow

  templates:
  - name: promote-flow
    steps:
      - - name: deploy-canary
          template: deploy
          arguments:
            parameters:
            - name: environment
              value: canary
      - - name: deploy-prod
          template: deploy
          arguments:
            parameters:
            - name: environment
              value: prod
