apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: promote-model
spec:
  entrypoint: promote-flow

  arguments:
    parameters:
    - name: source-environment
      value: staging
    - name: target-environment
      value: canary
    - name: model-version
      value: "v1.0.0"

  templates:
  - name: promote-flow
    inputs:
      parameters:
      - name: source-environment
      - name: target-environment
      - name: model-version
    steps:
      - - name: deploy
          template: deploy
          arguments:
            parameters:
            - name: environment
              value: "{{inputs.parameters.target-environment}}"
            - name: model-version
              value: "{{inputs.parameters.model-version}}"

  - name: deploy
    inputs:
      parameters:
      - name: environment
      - name: model-version
    container:
      image: argoproj/argocd:v2.9.3
      command: [/bin/sh, -c]
      args:
        - |
          set -e
          echo "Deploying version {{inputs.parameters.model-version}} to {{inputs.parameters.environment}} environment..."
          app_name="code-reviewer-{{inputs.parameters.environment}}"
          
          # Attempt to log in with retry mechanism
          max_attempts=3
          attempt=0
          while [ $attempt -lt $max_attempts ]; do
            argocd login argocd-server.argocd.svc.cluster.local \
              --username admin --password "$ARGOCD_PASSWORD" --insecure && break
            attempt=$((attempt + 1))
            sleep 5
          done
          
          if [ $attempt -eq $max_attempts ]; then
            echo "Failed to log in to ArgoCD after $max_attempts attempts"
            exit 1
          fi
          
          argocd app set "$app_name" --helm-set-string image.tag="{{inputs.parameters.model-version}}"
          argocd app sync "$app_name"
      env:
        - name: ARGOCD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: argocd-initial-admin-secret
              key: password