# train-model.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: train-model
spec:
  entrypoint: full-pipeline

  templates:
  - name: full-pipeline
    steps:
      - - name: trigger-training-endpoint
          template: call-endpoint
      - - name: build-and-deploy
          template: trigger-pipeline

  - name: call-endpoint
    container:
      image: curlimages/curl:7.85.0
      command: [sh, -c]
      args:
        - |
          echo "Triggering training endpoint..."
          code_version=$(curl -s http://training-service.default.svc.cluster.local/train)
          echo $code_version > /tmp/version
    volumeMounts:
    - name: workdir
      mountPath: /tmp

  - name: trigger-pipeline
    script:
      image: argoproj/argoexec:v3.4.7
      command: [sh, -c]
      source: |
        version=$(cat /tmp/version)
        echo "Starting full pipeline for version $version"
        argo submit --from workflowtemplate/build-container-image \ 
          -p model-version=$version --wait
        argo submit --from workflowtemplate/promote-workflow \ 
          -p source-environment=staging -p target-environment=canary \ 
          -p model-version=$version --wait
        argo submit --from workflowtemplate/promote-workflow \ 
          -p source-environment=canary -p target-environment=prod \ 
          -p model-version=$version --wait

  - name: workdir
    persistentVolumeClaim:
      claimName: pipeline-pvc

# This set of WorkflowTemplates exposes a single `train-model` entrypoint (`full-pipeline`) that triggers training, runs the build, then automatically deploys to staging, canary, and prod.
