FROM python:3.11-slim

WORKDIR /app

# Install FastAPI & Uvicorn
RUN pip install fastapi uvicorn

# Dummy app
COPY main.py .

# Start FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
