version: '3.8'

services:
  llama-code-review-fastapi:
    build: ./model_serving/llama_code_review_app
    container_name: llama-code-review-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./model_serving/llama_code_review_app:/app
      - /mnt/object:/mnt/object:ro
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    restart: always

volumes:
  grafana-storage:

