FROM python:3.11-slim
FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

WORKDIR /app

# Install FastAPI & Uvicorn
RUN pip install fastapi uvicorn

# Dummy app
COPY main.py .

# Start FastAPI app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
